version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - REPO_URI="${REPO_URI}"
      - IMAGE_TAG="latest"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG

      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"app","imageUri":"%s"}]' "$REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json



